spring.application.name=ai-symptom-service
server.port=8087

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Gemini API Configuration
# Replace with your actual Gemini API Key
gemini.api.key=${GEMINI_API_KEY:AIzaSyA3CSNx6ALE_uOtNyHYnYiAPtetMuLCGX8}
# Current valid models include gemini-1.5-flash or gemini-2.0-flash-exp
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent