spring.application.name=ai-symptom-service

server.port=8084

# Gemini API Details
#gemini.api.key=API_KEY
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/