package com.sliit.hospitalManagementSystem.payment_service.dto;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PayHereNotifyRequest {
	// The merchant identifier assigned by PayHere
	private String merchantId;
	// The unique identifier for the order/transaction
	private String orderId;
	// The payment ID generated by PayHere for this transaction
	private String paymentId;
	// The final amount paid by the customer
	private String payhereAmount;
	// The currency used for the payment (e.g., LKR, USD)
	private String payhereCurrency;
	// Status code indicating the outcome (e.g., 2 for success)
	private String statusCode;
	// MD5 hash signature for security validation
	private String md5sig;
	// The payment method used (e.g., VISA, MASTER, MOBILE_WALLET)
	private String method;
	// Human-readable status message from PayHere
	private String statusMessage;
}

