package com.sliit.hospitalManagementSystem.doctor_management.controller;

import com.sliit.hospitalManagementSystem.doctor_management.dto.PatientReportDTO;
import com.sliit.hospitalManagementSystem.doctor_management.service.PatientReportService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.lang.NonNull;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/doctors/reports")
@CrossOrigin(origins = "*")
public class PatientReportController {

    // Service for handling medical reports created by doctors for patients
    private final PatientReportService patientReportService;

    // Constructor based dependency injection
    public PatientReportController(PatientReportService patientReportService) {
        this.patientReportService = patientReportService;
    }

    // Creates a new medical report for a patient
    @PostMapping
    @PreAuthorize("hasRole('DOCTOR')")
    public ResponseEntity<PatientReportDTO> createReport(@RequestBody PatientReportDTO dto) {
        PatientReportDTO created = patientReportService.createReport(dto);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    // Retrieves a specific medical report by its unique ID
    @GetMapping("/{id}")
    public ResponseEntity<PatientReportDTO> getReportById(@PathVariable @NonNull Long id) {
        PatientReportDTO report = patientReportService.getReportById(id);
        return ResponseEntity.ok(report);
    }

    // Retrieves all medical reports generated by a specific doctor
    @GetMapping("/doctor/{doctorId}")
    public ResponseEntity<List<PatientReportDTO>> getReportsByDoctorId(@PathVariable @NonNull Long doctorId) {
        List<PatientReportDTO> reports = patientReportService.getReportsByDoctorId(doctorId);
        return ResponseEntity.ok(reports);
    }

    // Retrieves all medical reports belonging to a specific patient
    @GetMapping("/patient/{patientId}")
    public ResponseEntity<List<PatientReportDTO>> getReportsByPatientId(@PathVariable @NonNull Long patientId) {
        List<PatientReportDTO> reports = patientReportService.getReportsByPatientId(patientId);
        return ResponseEntity.ok(reports);
    }

    // Retrieves medical reports shared between a specific doctor and patient
    @GetMapping("/doctor/{doctorId}/patient/{patientId}")
    public ResponseEntity<List<PatientReportDTO>> getReportsByDoctorAndPatient(
            @PathVariable @NonNull Long doctorId, @PathVariable @NonNull Long patientId) {
        List<PatientReportDTO> reports = patientReportService.getReportsByDoctorAndPatient(doctorId, patientId);
        return ResponseEntity.ok(reports);
    }

    // Endpoint for doctors to append or update remarks on an existing medical report
    @PutMapping("/{id}/remarks")
    @PreAuthorize("hasRole('DOCTOR')")
    public ResponseEntity<PatientReportDTO> addDoctorRemarks(
            @PathVariable @NonNull Long id, @RequestBody Map<String, String> body) {
        String remarks = body.get("doctorRemarks");
        PatientReportDTO updated = patientReportService.addDoctorRemarks(id, remarks);
        return ResponseEntity.ok(updated);
    }
}
