spring.application.name=payment-service
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PayHere (Sandbox) configuration
payhere.sandbox=true
payhere.merchant-id=1235079
payhere.merchant-secret=

payhere.currency=LKR
payhere.return-url=${PAYHERE_RETURN_URL:http://localhost:5173/payment/success}
payhere.cancel-url=${PAYHERE_CANCEL_URL:http://localhost:5173/payment/cancel}
payhere.notify-url=${PAYHERE_NOTIFY_URL:http://localhost:8084/api/payments/payhere/notify}

# Notification Service Configuration
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8085}

# Appointment Service Configuration
appointment.service.url=${APPOINTMENT_SERVICE_URL:http://localhost:8082}
