package com.sliit.hospitalManagementSystem.doctor_management.repository;

import com.sliit.hospitalManagementSystem.doctor_management.model.PatientReport;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PatientReportRepository extends JpaRepository<PatientReport, Long> {

    // Retrieves all medical reports authorized or uploaded by a specific doctor
    List<PatientReport> findByDoctorId(Long doctorId);

    // Retrieves the complete medical report history for a specific patient
    List<PatientReport> findByPatientId(Long patientId);

    // Fetches reports that were specifically generated by a certain doctor for a certain patient
    List<PatientReport> findByDoctorIdAndPatientId(Long doctorId, Long patientId);

    // Lists all reports for a doctor, starting with the most recently uploaded ones
    List<PatientReport> findByDoctorIdOrderByUploadedAtDesc(Long doctorId);
}
