spring.application.name=notification-service
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nuwangavenuri24@gmail.com
spring.mail.password=rshhwroeueodjusm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# Test email with Api
# POST http://localhost:8085/api/notifications/email

# {
#   "to": "nuwangavenuri24@gmail.com",
#   "subject": "Testing MediConnect",
#   "body": "<h1>Success!</h1> <p>This email was sent from the Notification Service.</p>",
#   "html": true
# }


# http://localhost:8085/api/notifications/send

# {
#   "type": "APPOINTMENT_BOOKED",
#   "recipientName": "Venu",
#   "recipientEmail": "nuwangavenuri24@gmail.com",
#   "doctorName": "Smith",
#   "patientName": "Venu",
#   "appointmentDate": "2026-04-10",
#   "appointmentTime": "10:30 AM",
#   "appointmentId": "APT-001",
#   "specialty": "Cardiology"
# }
