spring.application.name=notification-service

server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Email (Gmail SMTP)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your-email@gmail.com
#spring.mail.password=your-gmail-app-password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio SMS
#twilio.account-sid=your-twilio-account-sid
#twilio.auth-token=your-twilio-auth-token
#twilio.from-number=+15005550006
